language: node_js
node_js: 10
dist: trusty

before_deploy:
  - cd dist
  - zip -r devsession-linux-$TRAVIS_TAG.zip devsession-gui-linux-x64
  - zip -r devsession-win-$TRAVIS_TAG.zip devsession-gui-win32-x64
  - cd ..

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: packages/website/build
    target_branch: gh-pages
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
    file:
      - dist/devsession-linux-$TRAVIS_TAG.zip
      - dist/devsession-win-$TRAVIS_TAG.zip